version: '3.7'
name: kalkulator_openmobi
services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    working_dir: /app
    environment:
      PHP_DATE_TIMEZONE: Europe/Warsaw
      PHP_MEMORY_LIMIT: 1024M
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_IDE_KEY: PHPSTORM
      PHP_IDE_CONFIG: 'serverName=kalkulator_openmobi'
    ports:
      - "8080:80"
    volumes:
      - ./:/app